/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chatserver;

import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author Webster
 */
public class TrieGUI extends javax.swing.JFrame {
    
    private TrieST<Integer> st;
    private String[] currentSuggestions;
    private String topSuggestions;
    private static final int NR = 4; 
            
    /**
     * Creates new form TrieGUI
     */
    public TrieGUI() {
        initComponents();
            currentSuggestions = new String[NR];
        
           txtIn.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent de) {
                if (txtIn.getText().isEmpty()) getSuggestions(null);
                if (!txtIn.getText().isEmpty()) getSuggestions(txtIn.getText());

                //System.out.println(txtIn.getText());
            }

            @Override
            public void removeUpdate(DocumentEvent de) {
                if (txtIn.getText().isEmpty()) getSuggestions(null);
                if (!txtIn.getText().isEmpty()) getSuggestions(txtIn.getText());
            }

            @Override
            public void changedUpdate(DocumentEvent de) {
            //Plain text components don't fire these events.
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtIn = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        suggestionOut = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInActionPerformed(evt);
            }
        });
        txtIn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtInKeyTyped(evt);
            }
        });

        suggestionOut.setColumns(20);
        suggestionOut.setRows(5);
        jScrollPane1.setViewportView(suggestionOut);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addComponent(txtIn))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtInKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInKeyTyped
  
    }//GEN-LAST:event_txtInKeyTyped
    
    public void getSuggestions(String typed){
        //Clear previous
        topSuggestions = null;

        //Get array of current suggestions and build output string
        if (typed != null){
        currentSuggestions = st.keysWithPrefixWeight(typed.toLowerCase());
        for (String s: currentSuggestions) {
                if (s==null && topSuggestions == null)      topSuggestions = "No further suggestions\n";
                if (s==null && topSuggestions != null)      topSuggestions += "\n";
                if (s!=null && topSuggestions != null)      topSuggestions += s + "\n";
                if (s!=null && topSuggestions == null)      topSuggestions = s + "\n";
             }
        //Output
        suggestionOut.setText(topSuggestions);}
        if (typed == null) suggestionOut.setText("");
        
    }
    
    private void txtInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrieGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrieGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrieGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrieGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrieGUI().setVisible(true);
            }
        });
    }
    
    public void setTrie(TrieST<Integer> trieIn){
        st = trieIn;
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea suggestionOut;
    private javax.swing.JTextField txtIn;
    // End of variables declaration//GEN-END:variables
}


